name: Labeller
on:
  push:
    branches:
      - release
  # pull_request:
  #   branches:
  #     - release

jobs:
  release:
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} addresses this.
