name: linting
on:
  pull_request:
    branches:
      - master
      - release

jobs:
  install-dependancies:
    name: install-dependancies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

  eslint:
    needs: install-dependancies
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: eslint
        run: npx eslint src/

  sass-lint:
    needs: install-dependancies
    name: sass-lint
    runs-on: ubuntu-latest
    steps:
      - name: sass-lint
        run: npm run build:styles

  lint-templates:
    needs: install-dependancies
    name: lint templates
    runs-on: ubuntu-latest
    steps:
      - name: Lint templates
        run: npm run build:templates
