name: 🤖 Release bot 

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Slackify the release body
      id: release_body
      uses: LoveToKnow/slackify-markdown-action@v1.0.0
      with:
        text: ${{ github.event.release.body }}
    - name: Announce on Slack 📢
      shell: bash
      run: |
        curl ${{ secrets.SLACK_WEBHOOK_URL }} \
          --request POST \
          --header 'Content-type: application/json' \
          --data \
            '{
              "title": "${{ github.event.release.name }}",
              "body": "${{ steps.release_body.outputs.text }}"
            }'
