name: 🤖 Release bot 

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Slackify the release body
      id: release_body
      uses: LoveToKnow/slackify-markdown-action@v1.0.0
      with:
        text: ${{ github.event.release.body }}
    - name: Announce on Slack 📢
      shell: bash
      run: |
        curl ${{ secrets.SLACK_WEBHOOK_URL }} \
          --request POST \
          --header 'Content-type: application/json' \
          --data \
            '{
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rocket: [Web] Loop Design System ${{ github.event.release.name }} has been released! :rocket:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.release.html_url }}|${{ github.event.release.name }} release notes on GitHub>"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.release_body.outputs.text }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Thanks for using the <https://github.com/BTplc/loop-next|Loop Design System>!"
                  }
                }
              ]
            }'
